@AuthenticationService_HostAddress = http://localhost:8080

POST {{AuthenticationService_HostAddress}}/authentication/user/signup/
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "email": "test1@test.com",
    "password": "test12345678",
    "firstName": "Max",
    "lastName": "Muster"
}

###

POST {{AuthenticationService_HostAddress}}/authentication/user/login/
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
    "email": "test1@test.com",
    "password": "test12345678"
}

###

POST {{AuthenticationService_HostAddress}}/authentication/user/refresh
Accept-Language: en-US,en;q=0.5
Cookie: .AspNetCore.Cookies=CfDJ8JC7JDLcrnJDnNB1_J8eHwE5xVndMFMCBQV8iteIzdGA5l3an2-qfqRgiMKL70ILUriQlG95J1zSwQeP5ICJtAveiLNhCUc250tUmvnkLbCn1D8jJqIq9djMf2TOIHAk5ruiRfo2BqHzYe9SeU2CaGArbyTUcu_VV75sPfOhV3Wk_dhfgALTjD4iKI7Pao0a-i2yJKFIj6xYX0lYlPfTCgj0zTpNIi3BgjYEdtVtfoFfrom0Sm_kjKGfmSkyJYANKwEcT_cGpmbV8Yd55eMTWfFB9sxywO0n2odc14DQ3nypIW-168MlCTrMnXX35Hg8dSlVncrdCcvnDRMgUbZXb-i0OMeWC6AS53IBjpSFLYFeFVhw4MrWypEcptCu5Z-I6Eao7zw0oURTwRWtudZv2TY; path=/; secure; samesite=lax; httponly

###

POST {{AuthenticationService_HostAddress}}/authentication/user/logout
Accept-Language: en-US,en;q=0.5
Cookie: .AspNetCore.Cookies=CfDJ8FpGOVFD-3NNvUmDvhgJIrmITRbgMQwWWaNhHjkUwX6JVPahNXvhvTyzPREdd2nm4tkLCB0_ArSrDAEvXQiCcHPtzXrAyEUXyw0Ou7NXcnkW66HP8Obfc1YRkGa2_ExAsBusuMrIe3WyNGgfAQ4EM7Vg3oQyPWNLcByX20zpBJ4U3XClkEv07iIQJmvC9RVbXYKcJlovOrvjofs9LZN1slsBNVfCkQd8MtNEwl68-kQqMkJ3dRPl5wWp991sp9aLtQpXJKyQaToOrLE-tQOP7B9cDMIsXHZiTtvZ9eXWR11KOeA8j83xDrx5NYqV7Reh71bBG73BlfZ3iIZuxEwSrbRNFoNgWZnW1yMJ5OLxmBZe0lCYstxmMM2RLS-EpqDlPnD2RXuZk3zQ8AaLppkluEY; path=/; secure; samesite=lax; httponly

###