receivers:
  otlp:
    protocols:
      grpc:
      http:

extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "otel-logs"

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: json

processors:
  batch:
    timeout: 5s
    send_batch_size: 1

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]