global using FluentValidation;
global using InventoryService.Dtos;
global using InventoryService.Queries;
global using Microsoft.AspNetCore.Mvc;
global using Service.Base.Api.CQRS;
global using Service.Base.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text.Json.Serialization;
