@GatewayService_HostAddress = https://gateway.ecom.dev/api/

POST {{GatewayService_HostAddress}}/inventory/categories
Accept: application/json
Content-Type: application/json

{
    "Id": "0000"
}

###
